<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yate</string>
	</array>
	<key>name</key>
	<string>Yate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#match</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include-file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#func</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#jpath</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#yate-strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#yate-strings-single-quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comments</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<key>block-definition</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-attributes</string>
				</dict>
			</array>
		</dict>
		<key>controls</key>
		<dict>
			<key>match</key>
			<string>\b(if|else|elseif|for|apply)\b</string>
			<key>name</key>
			<string>keyword.controls</string>
		</dict>
		<key>func</key>
		<dict>
			<key>begin</key>
			<string>^(?:\s|	)*(func|key)(?:	|\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?={)</string>
			<key>name</key>
			<string>source.yate.func</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#func-definition</string>
				</dict>
			</array>
		</dict>
		<key>func-definition</key>
		<dict>
			<key>begin</key>
			<string>(?:([a-zA-Z_$][a-zA-Z_$-0-9]*))(\s|\t)*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>source.yate.func.def</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(nodeset)\b</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\b|\s|\t)=(?:\b|\s|\t)</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath-operators</string>
				</dict>
			</array>
		</dict>
		<key>html</key>
		<dict>
			<key>begin</key>
			<string>^(\s|\t)*(?=&lt;)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-inline-strings</string>
				</dict>
			</array>
		</dict>
		<key>html-attributes</key>
		<dict>
			<key>begin</key>
			<string>(?=(\s||\t))</string>
			<key>end</key>
			<string>(?=((&gt;|/&gt;)))</string>
			<key>name</key>
			<string>source.yate.html.tag.attribute</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-strings-single-quoted</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z0-9:_-]+\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
			</array>
		</dict>
		<key>html-definition</key>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)\s*([-_a-zA-Z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.yate.html.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-attributes</string>
				</dict>
			</array>
		</dict>
		<key>include-file</key>
		<dict>
			<key>match</key>
			<string>\b(include|import|module|external)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<key>inline-comments</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<key>inline-expression</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)({)(?!\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\})(})(?!\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.yate.inline-expression</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
			</array>
		</dict>
		<key>jpath</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|\t|\[|\(|[{,!]|/)(\.|/)(\.|[a-zA-Z0-9_-]|\*|\$)*(?=\s|\t|\[|\]|\)|[,}])</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>jpath-operators</key>
		<dict>
			<key>match</key>
			<string>(\||\[|\])</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>match</key>
		<dict>
			<key>begin</key>
			<string>^(?:\s|\t)*(match)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?={)</string>
			<key>name</key>
			<string>source.yate.match</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jpath-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yate-strings-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>((?&lt;=\s|\t|\))(&amp;&amp;|\|\|)(?=\s|\t|\())|((=|!=|==|!==|===|!|/|\+|%|&gt;|&lt;|&gt;=|&lt;=|\[|\]))</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>match</key>
			<string>("|')([^"']*)("|')</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>yate-attributes</key>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z]([a-zA-Z0-9_-]|\:)*</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>yate-inline-strings</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=&gt;)(?!\&lt;|$)</string>
			<key>end</key>
			<string>(?=\&lt;|$)</string>
			<key>name</key>
			<string>source.yate.inline-string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^"'&lt;&gt;{}/]+)</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\{\{|\}\})</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>yate-strings</key>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.yate.string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^"{}])*</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\{\{|\}\})</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>yate-strings-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.yate.string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^'{}])*</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\{\{|\}\})</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yate</string>
	<key>uuid</key>
	<string>fa6fe8fe-4c7b-419a-9554-b0bc923cae37</string>
</dict>
</plist>
